version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Berlin"
    assignees:
      - "bierdosenhalter"
    reviewers:
      - "bierdosenhalter"
    commit-message:
      prefix: "maven"
      include: "scope"