name: Publish package to GitHub Packages

on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Get commit info
        run: echo "SHA=$GITHUB_SHA" >> $GITHUB_ENV

      - name: Prepare release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Minecraft 1.12.2
            Automated release at commit ${{ env.SHA }}
          draft: false
          prerelease: false

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Prepare depdendency cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          restore-keys: "${{ runner.os }}-m2"

      - name: Maven package
        run: mvn --batch-mode --show-version --errors package --file pom.xml

      - name: upload release asset
        uses: csexton/release-asset-action@v2
        with:
          pattern: "target/*.jar"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
